[tool.poetry]
name = "mlsystemdesign"
version = "0.1.0"
description = ""
authors = ["Nikita Borisov <nik-everyday@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
yfinance = "^0.2.28"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
